import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const studioPage = readFileSync("app/studio/page.tsx", "utf8");
const studioActions = readFileSync("app/components/studio-actions.tsx", "utf8");
const forms = readFileSync("app/components/forms.tsx", "utf8");
const businessWizard = readFileSync("app/components/business-profile-wizard.tsx", "utf8");
const studioService = readFileSync("src/modules/studio/service.ts", "utf8");
const campaignsRoute = readFileSync("app/api/campaigns/route.ts", "utf8");
const media = readFileSync("src/modules/studio/media.ts", "utf8");
const imageProvider = readFileSync("src/modules/studio/providers/image/openai-provider.ts", "utf8");
const videoProvider = readFileSync("src/modules/studio/providers/video/openai-provider.ts", "utf8");
const metaProvider = readFileSync("src/modules/studio/providers/social/meta/index.ts", "utf8");
const settings = readFileSync("app/studio/page.tsx", "utf8");

for (const [label, route] of [
  ["Create Campaign", "/studio?section=campaigns"],
  ["Generate Poster", "/studio?section=create"],
  ["Create Social Content", "/studio?section=create"],
  ["Upload Image", "/studio?section=media"],
  ["Upload Video", "/studio?section=media"],
  ["Open Brand Kit", "/studio?section=brand"],
  ["View Media Library", "/studio?section=media"],
]) {
  assert.ok(studioPage.includes(label), `overview quick action exists: ${label}`);
  assert.ok(studioPage.includes(route), `overview quick action routes inside Studio: ${label}`);
}

for (const [label, endpoint] of [
  ["Generate Content", "/api/studio/generate"],
  ["Generate Poster", "/api/studio/poster"],
  ["Storyboard", "/api/studio/storyboard"],
  ["Approve", "/api/campaigns"],
  ["Run Studio Intelligence", "/api/studio/extract"],
  ["Use in Business", "/api/studio/placements"],
  ["Media Approve", "/api/media-library/"],
]) {
  assert.ok(studioActions.includes(endpoint), `${label} is wired to ${endpoint}`);
}

assert.ok(studioActions.includes("router.refresh()"), "Studio actions refresh after mutations");
assert.ok(studioActions.includes("Generating..."), "content generation has loading state");
assert.ok(studioActions.includes("Generating Poster..."), "poster generation has loading state");
assert.ok(studioActions.includes("Video generation is not available yet."), "video action states unavailable provider without fake success");
assert.ok(studioActions.includes("Copy Storyboard"), "storyboard remains copyable when video generation is unavailable");
assert.ok(studioActions.includes("Download Storyboard"), "storyboard remains downloadable when video generation is unavailable");
assert.ok(studioActions.includes("Create Video/Reel"), "manual reel/video workflow entry remains visible from storyboards");
assert.ok(studioActions.includes('job.status === "FAILED"') && studioActions.indexOf('job.status === "FAILED"') < studioActions.indexOf('setMessage("Video job queued. Check Processing for status.")'), "failed video provider result is handled before any queued success message");
assert.ok(studioActions.includes("Connect Meta account in Settings before publishing."), "publish action states Meta limitation");
assert.ok(campaignsRoute.includes("approveCampaign"), "campaign approval API uses service action");
assert.ok(studioService.includes("approvedAt: now"), "approval persists output approvedAt");
assert.ok(studioService.includes('status: "APPROVED"'), "approval persists campaign status");
assert.ok(media.includes('metadataJson: { templateMode: "demo-svg"'), "poster generation is accurately labelled deterministic demo SVG");
assert.ok(media.includes("composeBrandedPoster"), "poster generation uses deterministic brand composition for AI images");
assert.ok(imageProvider.includes("client.images.generate"), "OpenAI image provider uses official SDK image generation");
assert.ok(imageProvider.includes("STUDIO_IMAGE_MODEL") || imageProvider.includes("studioImageConfig"), "OpenAI image provider reads centralized image model config");
assert.ok(!imageProvider.includes("response_format"), "OpenAI GPT image requests do not send unsupported response_format");
assert.ok(imageProvider.includes('output_format: "png"'), "OpenAI GPT image requests ask for PNG output");
assert.ok(imageProvider.includes("decodeOpenAIImageData"), "OpenAI image provider decodes base64 image data");
assert.ok(imageProvider.includes('Buffer.from(image.b64_json, "base64")'), "OpenAI image provider decodes b64_json into bytes");
assert.ok(media.includes('writeGeneratedBuffer(campaign.companyId, "generated/source", `${randomUUID()}.png`, generated.bytes)'), "OpenAI generated bytes are stored as a PNG source asset");
{
  const mockB64 = Buffer.from("mock png bytes").toString("base64");
  const decoded = Buffer.from(mockB64, "base64");
  assert.equal(decoded.toString(), "mock png bytes", "mocked OpenAI b64_json image data decodes before storage");
}
assert.ok(videoProvider.includes("https://api.openai.com/v1/videos"), "OpenAI video provider uses Videos API");
assert.ok(metaProvider.includes("instagram_content_publish"), "Meta provider requests Instagram publishing scope");
assert.ok(metaProvider.includes("isPublicHttpsUrl"), "Meta publishing blocks non-public media URLs");
assert.ok(settings.includes("Connect Meta"), "Studio Settings exposes Meta connection action");
assert.ok(settings.includes("Image readiness"), "Studio Settings shows image provider readiness");
assert.ok(settings.includes("Video readiness"), "Studio Settings shows video provider readiness");
assert.ok(studioPage.includes("Apply filters"), "media filters are functional form controls");
assert.ok(studioPage.includes("Retry unavailable"), "processing retry is not a dead button");
assert.ok(studioPage.includes('job.status === "FAILED" && providerReady'), "processing retry remains gated by provider readiness");
assert.ok(studioPage.includes("Use Template"), "templates provide a Studio create workflow entry");
assert.ok(studioPage.includes("+ Add Business"), "Studio header exposes Add Business action");
assert.ok(studioPage.includes("mode=create"), "Add Business opens Business Profile wizard in create mode");
assert.ok(studioPage.includes("companyQuery"), "Studio navigation preserves active company scope");
assert.ok(businessWizard.includes('mode?: "create" | "edit"'), "Business Profile wizard supports explicit create/edit modes");
assert.ok(businessWizard.includes("existingBusinesses.find"), "Business Profile wizard prevents duplicate workspace slugs");
assert.ok(businessWizard.includes("slugify(value)"), "Business Profile wizard auto-generates editable workspace slug");
assert.ok(businessWizard.includes("const targetCompany = savedCompany.slug ?? savedCompany.id ?? draft.slug"), "Create mode redirects to the new active business");
assert.ok(businessWizard.includes("blankDraft"), "Create mode starts from blank profile data");
assert.ok(businessWizard.includes("BusinessDraft"), "Business Profile wizard uses one parent-level draft object");
assert.ok(businessWizard.includes("sessionStorage.setItem(key, JSON.stringify(draft))"), "Business Profile wizard persists unfinished drafts in session storage");
assert.ok(businessWizard.includes('saveState === "saving" ? "Saving..."'), "Business Profile final save shows an in-flight Saving state");
assert.ok(businessWizard.includes('saveState === "saved" ? "Saved ✓"'), "Business Profile final save confirms Saved state");
assert.ok(businessWizard.includes("step < steps.length - 1"), "Business Profile final step does not render a Next action");
assert.ok(businessWizard.includes("Save & Finish"), "Business Profile edit mode uses a clear final save label");
assert.ok(businessWizard.includes("router.push(`/studio?company=${encodeURIComponent(targetCompany)}&section=overview`)"), "Business Profile save redirects to Studio overview after persistence");
assert.ok(businessWizard.includes("completionPercent(draft)"), "completion percentage is calculated from current draft");
assert.ok(businessWizard.includes("missingFields(draft, step)"), "Next validates only the active step");
assert.ok(businessWizard.includes("finalMissing"), "Create button enablement uses explicit final required fields");
assert.ok(businessWizard.includes("A business with workspace URL"), "duplicate SettleSmart Works create attempts show a clear open-existing message");
assert.ok(businessWizard.includes("Open {duplicateBusiness.name}"), "duplicate slug warning provides an Open existing business action");
assert.ok(businessWizard.includes("BrandAssetUpload"), "Business Profile identity step uses direct brand asset upload controls");
assert.ok(businessWizard.includes('form.append("target", "brand")'), "brand asset uploads reuse /api/uploads with target=brand");
assert.ok(businessWizard.includes('form.append("brandField", field)'), "brand asset uploads identify the target BrandProfile field");
assert.ok(businessWizard.includes("onDrop"), "brand asset upload cards support drag and drop");
assert.ok(businessWizard.includes("Use external URL"), "external URL remains secondary to device upload");
assert.ok(businessWizard.includes("Remove"), "brand asset cards can remove draft paths");
assert.ok(businessWizard.includes("Replace"), "brand asset cards can replace uploaded files");
assert.ok(businessWizard.includes("image/png,image/svg+xml,image/webp"), "logo upload accepts PNG, SVG and WEBP");
assert.ok(businessWizard.includes("image/png,image/svg+xml,image/x-icon"), "favicon upload accepts PNG, SVG and ICO");

const uploadRoute = readFileSync("app/api/uploads/route.ts", "utf8");
const storage = readFileSync("src/modules/wave1/storage.ts", "utf8");
assert.ok(uploadRoute.includes("logoMimeTypes"), "upload route validates logo MIME types");
assert.ok(uploadRoute.includes("faviconMimeTypes"), "upload route validates favicon MIME types");
assert.ok(uploadRoute.includes("maxMb: isFavicon ? 2 : 5"), "upload route enforces brand asset size limits");
assert.ok(uploadRoute.includes('assetType: "LOGO"'), "saved company brand uploads create BrandAsset LOGO records");
assert.ok(uploadRoute.includes("manualImageMimeTypes"), "manual poster uploads have explicit image MIME validation");
assert.ok(uploadRoute.includes("maxMb: 10"), "manual poster uploads enforce 10MB size limit");
assert.ok(uploadRoute.includes('sourceType: "UPLOADED"'), "manual poster uploads are labelled uploaded, not generated");
assert.ok(uploadRoute.includes("campaignId") && uploadRoute.includes("Campaign does not belong to selected company"), "manual uploads validate campaign ownership");
assert.ok(uploadRoute.includes("dimensionWarning"), "manual uploads store platform dimension warnings");
assert.ok(storage.includes('["svg", "image/svg+xml"]'), "shared storage supports SVG uploads");
assert.ok(storage.includes('["ico", "image/x-icon"]'), "shared storage supports ICO uploads");
assert.ok(forms.includes("Campaign") && forms.includes("Platform") && forms.includes("Caption / Description"), "Upload Media captures campaign, platform and caption");
assert.ok(forms.includes("Title") && forms.includes("Media Type") && forms.includes("Category") && forms.includes("File"), "Upload Media fields have visible labels");
assert.ok(forms.includes("Uploaded media is saved as Source: Uploaded"), "Upload Media explains manual source labelling");
assert.ok(studioActions.includes("Upload My Poster"), "Create/Campaign poster failure offers manual upload fallback");
assert.ok(studioActions.includes("Retry AI Generation"), "poster failure offers AI retry");
assert.ok(studioActions.includes("Generate Template Poster"), "poster failure offers template fallback");
assert.ok(studioActions.includes("Create from this media"), "approved media exposes next-step creation actions");
assert.ok(studioActions.includes("Publish to Social"), "social publishing is hidden behind an explicit button");
assert.ok(studioActions.includes("Use in Business / Commerce"), "Commerce placement controls are hidden behind an explicit action");
assert.ok(studioService.includes("visualReference"), "storyboards can use uploaded campaign media as visual reference");
assert.ok(studioService.includes("mediaAssetId") && studioService.includes("Selected storyboard media does not belong to this campaign"), "storyboard can target a selected campaign media asset safely");

console.log("Studio action contract tests passed.");
