ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_COLLECTED';
ALTER TYPE "NotificationEventType" ADD VALUE IF NOT EXISTS 'PAYMENT_COLLECTED';
ALTER TYPE "NotificationEventType" ADD VALUE IF NOT EXISTS 'RECEIPT_READY';
